name: movies_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.11.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
